global using FakeItEasy;
global using FluentAssertions;
global using JetBrains.Annotations;
global using Mapster;
global using MediatR;
global using Motorent.TestUtils.Constants;
global using Motorent.TestUtils.Factories;
global using ResultExtensions;
global using ResultExtensions.FluentAssertions;