POST {{base_url}}/v1/users/register
Accept: application/json
Content-Type: application/json

{
  "role": "renter",
  "name": "John Doe",
  "email": "john@doe981.com",
  "password": "JohnDoe123",
  "birthdate": "2000-01-01"
}

> {% 
if (response.status === 200) {
  client.global.set('access_token', response.body.access_token);
}
%}