global using MotorcycleRental.AdminManagementService.Api.Config.Extensions;
global using MotorcycleRental.AdminManagementService.Api.Config.Middlewares;
global using MotorcycleRental.AdminManagementService.Service;
global using MotorcycleRental.AdminManagementService.Service.UseCases.MotorcycleUseCase.AddMotorcycle;
global using MotorcycleRental.AdminManagementService.Service.UseCases.MotorcycleUseCase.DeleteMotocycle;
global using MotorcycleRental.AdminManagementService.Service.UseCases.MotorcycleUseCase.GetMotorcycleByPlate;
global using MotorcycleRental.AdminManagementService.Service.UseCases.MotorcycleUseCase.UpdateMotocycle;
global using MotorcycleRental.Infraestructure;
global using MotorcycleRental.Infraestructure.MessageBus;

